from enum import Enum


class HTTPStatusCodes(Enum):
    OK = 200
    CREATED = 201
    BAD_REQUEST = 400
    FORBIDDEN = 403
    NOT_FOUND = 404
    UNPROCESSABLE_ENTITY = 422
    INTERNAL_SERVER_ERROR = 500


class ErrorCodes(Enum):
    RESOURCE_NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    EMPTY_CONTENT = "EMPTY_CONTENT"
    INVALID_ID = "INVALID_ID"
    PROJECT_ACCESS_DENIED = "PROJECT_ACCESS_DENIED"
